FROM n8nio/n8n

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ARG USERNAME
ARG PASSWORD

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$PASSWORD

ENV ENABLE_ALPINE_PRIVATE_NETWORKING=true

ARG ENCRYPTION_KEY
ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY

ARG N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true


ARG N8N_HOST
ARG WEBHOOK_TUNNEL_URL
ARG WEBHOOK_URL

ENV N8N_HOST=$N8N_HOST
ENV WEBHOOK_TUNNEL_URL=$WEBHOOK_TUNNEL_URL
ENV WEBHOOK_URL=$WEBHOOK_URL



CMD ["start"]
